// examples/sveltekit/src/routes/comments.svelte
<script context="module" lang="ts">
	// import { KitQLInfo } from '@kitql/all-in';
	import CommentItem from '$lib/components/hackernews/comment/CommentItem.svelte';
	import Loading from '$lib/components/layout/Loading.svelte';
	import Button from '$lib/components/supabase/ui/Button.svelte';
	import { KQL_CommentsRouteQuery } from '$lib/graphql/_kitql/graphqlStores';
	import { onMount } from 'svelte';

	export async function load({ fetch }) {
		await KQL_CommentsRouteQuery.queryLoad({ fetch });
		return {};
	}
</script>

<script lang="ts">
	let infiniteList = [];

	onMount(async () => {
		await KQL_CommentsRouteQuery.query();
		infiniteList = $KQL_CommentsRouteQuery.data?.comments?.edges ?? [];
	});

	async function loadMore(cursor: string) {
		const newData = await KQL_CommentsRouteQuery.query({
			variables: { after: cursor }
		});
		infiniteList = [...infiniteList, ...newData.data?.comments?.edges];
	}
</script>

<svelte:head>
	<title>supanews | Comments</title>
</svelte:head>

<!-- Just for development help ✅ -->
<!-- <KitQLInfo store={KQL_CommentsRouteQuery} /> -->

<section class="text-gray-600 body-font overflow-hidden w-full">
	<div class="container px-3 py-24 mx-auto">
		<div class="-my-8 divide-y-2 divide-gray-100">
			{#each infiniteList as edge}
				<CommentItem comment={edge.node} />
			{:else}
				{#if $KQL_CommentsRouteQuery.status !== 'NEVER'}
					<Loading />
					{#each new Array(10) as item}
						<CommentItem comment={null} />
					{/each}
				{:else}
					No data!
				{/if}
			{/each}
			{#if $KQL_CommentsRouteQuery.isFetching}
				<Loading />
			{/if}
		</div>
	</div>

	<div class="flex justify-center content-center">
		<Button on:click={() => loadMore($KQL_CommentsRouteQuery.data?.comments?.pageInfo.endCursor)}
			>Load more.</Button
		>
	</div>
</section>

// app/pages/comments.tsx
import { Button } from "@supabase/ui";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useQuery } from "urql";
import { gql } from "../gql";
import { CommentItem } from "../lib/comment-item";
import { Container } from "../lib/container";
import { Loading } from "../lib/loading";
import { MainSection } from "../lib/main-section";
import { usePaginatedQuery } from "../lib/use-paginated-query";

const CommentsRouteQuery = gql(/* GraphQL */ `
  query CommentsRouteQuery($after: Cursor) {
    comments: commentCollection(
      orderBy: [{ createdAt: DescNullsFirst }]
      first: 15
      after: $after
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          ...CommentItem_CommentFragment
        }
      }
    }
  }
`);

const Comments: NextPage = () => {
  const [lastCursor, setLastCursor] = React.useState<string | undefined>(
    undefined
  );
  const [commentsQuery] = usePaginatedQuery({
    query: CommentsRouteQuery,
    variables: {
      after: lastCursor,
    },
    mergeResult(oldData, newData) {
      return {
        ...oldData,
        ...newData,
        comments: {
          ...oldData.comments!,
          ...newData.comments!,
          edges: [...oldData.comments!.edges, ...newData.comments!.edges],
        },
      };
    },
  });

  return (
    <Container>
      <MainSection>
        <Head>
          <title>supanews | Comments</title>
          <meta name="description" content="New comments" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="text-gray-600 body-font overflow-hidden w-full">
          <div className="container px-3 py-24 mx-auto">
            <div className="-my-8 divide-y-2 divide-gray-100">
              {commentsQuery?.data?.comments?.edges.map((edge) => (
                <CommentItem comment={edge.node!} key={edge.cursor} />
              ))}
            </div>
            {commentsQuery.fetching ? <Loading /> : null}
          </div>
          {commentsQuery.data?.comments?.pageInfo.hasNextPage ? (
            <div className="flex justify-center content-center">
              <Button
                onClick={() =>
                  setLastCursor(
                    commentsQuery.data?.comments?.pageInfo.endCursor ??
                      undefined
                  )
                }
              >
                Load more.
              </Button>
            </div>
          ) : null}
        </section>
      </MainSection>
    </Container>
  );
};

export default Comments;
