// app/pages/newest.tsx
import { Auth, Button } from "@supabase/ui";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { gql } from "../gql";
import { Container } from "../lib/container";
import { FeedItem } from "../lib/feed-item";
import { Loading } from "../lib/loading";
import { MainSection } from "../lib/main-section";
import { noopUUID } from "../lib/noop-uuid";
import { usePaginatedQuery } from "../lib/use-paginated-query";

const NewestRouteQuery = gql(/* GraphQL */ `
  query NewestRouteQuery($profileId: UUID!, $after: Cursor) {
    feed: postCollection(
      orderBy: [{ createdAt: DescNullsFirst }]
      first: 15
      after: $after
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          ...FeedItem_PostFragment
        }
      }
    }
  }
`);

const Newest: NextPage = () => {
  const { user } = Auth.useUser();
  const [lastCursor, setLastCursor] = React.useState<string | undefined>(
    undefined
  );
  const [newestQuery] = usePaginatedQuery({
    query: NewestRouteQuery,
    variables: {
      profileId: user?.id ?? noopUUID,
      after: lastCursor,
    },
    mergeResult(oldData, newData) {
      return {
        ...oldData,
        ...newData,
        feed: {
          ...oldData.feed!,
          ...newData.feed!,
          edges: [...oldData.feed!.edges, ...newData.feed!.edges],
        },
      };
    },
  });

  return (
    <Container>
      <Head>
        <title>supanews | Newest</title>
        <meta name="description" content="What is hot?" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainSection>
        <section className="text-gray-600 body-font overflow-hidden w-full">
          <div className="container px-5 py-24 mx-auto">
            <div className="-my-8">
              {newestQuery?.data?.feed?.edges.map((edge) => (
                <FeedItem post={edge.node!} key={edge.cursor} />
              ))}
            </div>
            {newestQuery.fetching ? <Loading /> : null}
          </div>
          {newestQuery.data?.feed?.pageInfo.hasNextPage ? (
            <div className="flex justify-center content-center">
              <Button
                onClick={() => {
                  setLastCursor(
                    newestQuery.data?.feed?.pageInfo.endCursor ?? undefined
                  );
                }}
              >
                Load more.
              </Button>
            </div>
          ) : null}
        </section>
      </MainSection>
    </Container>
  );
};

export default Newest;

// examples/sveltekit/src/routes/newest.svelte
<script context="module" lang="ts">
	// import { KitQLInfo } from '@kitql/all-in';
	import FeedItem from '$lib/components/FeedItem.svelte';
	import Loading from '$lib/components/layout/Loading.svelte';
	import Button from '$lib/components/supabase/ui/Button.svelte';
	import { KQL_NewestRouteQuery } from '$lib/graphql/_kitql/graphqlStores';
	import { noopUUID } from '$lib/utils/noop-uuid';
	import { onMount } from 'svelte';

	export async function load({ fetch }) {
		await KQL_NewestRouteQuery.queryLoad({ fetch, variables: { profileId: noopUUID } });
		return {};
	}
</script>

<script lang="ts">
	let infiniteList = [];

	onMount(async () => {
		await KQL_NewestRouteQuery.query({ fetch, variables: { profileId: noopUUID } });
		infiniteList = $KQL_NewestRouteQuery.data?.feed?.edges ?? [];
	});

	async function loadMore(cursor: string) {
		const newData = await KQL_NewestRouteQuery.query({
			variables: { profileId: noopUUID, after: cursor }
		});
		infiniteList = [...infiniteList, ...newData.data?.feed?.edges];
	}
</script>

<svelte:head>
	<title>supanews | Newest</title>
</svelte:head>

<!-- Just for development help ✅ -->
<!-- <KitQLInfo store={KQL_NewestRouteQuery} /> -->

<section class="text-gray-600 body-font overflow-hidden w-full">
	<div class="container px-3 py-24 mx-auto">
		<div class="-my-8">
			{#each infiniteList as edge}
				<FeedItem post={edge.node} />
			{:else}
				{#if $KQL_NewestRouteQuery.status === 'LOADING'}
					<Loading />
					{#each new Array(10) as item}
						<FeedItem post={null} />
					{/each}
				{:else}
					No data!
				{/if}
			{/each}
			{#if $KQL_NewestRouteQuery.isFetching}
				<Loading />
			{/if}
		</div>
	</div>

	<div class="flex justify-center content-center">
		<Button on:click={() => loadMore($KQL_NewestRouteQuery.data?.feed?.pageInfo.endCursor)}
			>Load more.</Button
		>
	</div>
</section>
