// app/lib/footer.tsx
import Image from "next/image";
import Link from "next/link";

export function Footer() {
  const navigation = {
    main: [{ name: "🤔 How did we build this app?", href: "/about" }],
    social: [
      {
        name: "Twitter",
        href: "https://twitter.com/supabase",
        icon: (props: any) => (
          <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
            <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
          </svg>
        ),
      },
      {
        name: "GitHub",
        href: "https://github.com/supabase-community/supabase-graphql-example",
        icon: (props: any) => (
          <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
            <path
              fillRule="evenodd"
              d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
              clipRule="evenodd"
            />
          </svg>
        ),
      },
    ],
  };

  return (
    <footer className="bg-white">
      <div className="max-w-7xl mx-auto py-4 px-4 overflow-hidden sm:px-6 lg:px-8">
        <div className="bg-white">
          <div className="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-2 gap-8 md:grid-cols-2 lg:grid-cols-2">
              <div className="col-span-1 flex justify-center md:col-span-2 lg:col-span-1">
                <a href="https://www.supabase.com">
                  <img
                    className="h-12"
                    src="/supabase-logo-wordmark--light.svg"
                    alt="Supabase"
                  />
                </a>
              </div>
              <div className="col-span-1 flex justify-center md:col-span-2 lg:col-span-1">
                <a href="https://www.the-guild.dev">
                  <img
                    className="h-12"
                    src="/the-guild-full-dark.svg"
                    alt="The Guild"
                  />
                </a>
              </div>
            </div>
          </div>
        </div>
        <nav
          className="-mx-5 -my-2 flex flex-wrap justify-center"
          aria-label="Footer"
        >
          {navigation.main.map((item) => (
            <div key={item.name} className="px-5 py-2">
              <Link href={item.href}>
                <a className="text-base text-gray-500 hover:text-gray-900">
                  {item.name}
                </a>
              </Link>
            </div>
          ))}
        </nav>
        <div className="mt-8 flex justify-center space-x-6">
          {navigation.social.map((item) => (
            <a
              key={item.name}
              href={item.href}
              className="text-gray-400 hover:text-gray-500"
            >
              <span className="sr-only">{item.name}</span>
              <item.icon className="h-6 w-6" aria-hidden="true" />
            </a>
          ))}
        </div>
      </div>
    </footer>
  );
}

// examples/sveltekit/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import Icons from './Icons.svelte';

	const navigation = {
		main: [{ name: '🤔 How did we build this app?', href: '/about' }],
		social: [
			{
				name: 'Twitter',
				href: 'https://twitter.com/supabase',
				icon: 'Twitter'
			},
			{
				name: 'GitHub',
				href: 'https://github.com/supabase-community/supabase-graphql-example',
				icon: 'GitHub'
			}
		]
	};
</script>

<footer class="bg-white">
	<div class="max-w-7xl mx-auto py-4 px-4 overflow-hidden sm:px-6 lg:px-8">
		<div class="bg-white">
			<div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
				<div class="grid grid-cols-2 gap-8 md:grid-cols-2 lg:grid-cols-2">
					<div class="col-span-1 flex justify-center md:col-span-2 lg:col-span-1">
						<a href="https://www.supabase.com">
							<img class="h-12" src="/supabase-logo-wordmark--light.svg" alt="Supabase" />
						</a>
					</div>
					<div class="col-span-1 flex justify-center md:col-span-2 lg:col-span-1">
						<a href="https://www.the-guild.dev">
							<img class="h-12" src="/the-guild-full-dark.svg" alt="The Guild" />
						</a>
					</div>
				</div>
			</div>
		</div>
		<nav class="-mx-5 -my-2 flex flex-wrap justify-center" aria-label="Footer">
			{#each navigation.main as item}
				<div class="px-5 py-2">
					<a href={item.href} class="text-base text-gray-500 hover:text-gray-900">
						{item.name}
					</a>
				</div>
			{/each}
		</nav>
		<div class="mt-8 flex justify-center space-x-6">
			{#each navigation.social as item}
				<a href={item.href} class="text-gray-400 hover:text-gray-500">
					<span class="sr-only">{item.name}</span>
					<Icons name={item.icon} class="h-6 w-6" />
				</a>
			{/each}
		</div>
	</div>
</footer>
